### ISSUE TITLE
clash不支持mips_24kc 啊

### ISSUE THREAD

**Issue by zcracker** [antonchen/clash-for-openwrt#1]
clash的Makefile文件里面好像没有这个，仅仅支持以下cpu
ifeq ($(ARCH),mipsel)
PKG_ARCH:=mipsle
endif
ifeq ($(ARCH),mips)
PKG_ARCH:=mips64
endif
ifeq ($(ARCH),i386)
PKG_ARCH:=386
endif
ifeq ($(ARCH),x86_64)
PKG_ARCH:=amd64
endif
ifeq ($(ARCH),arm)
PKG_ARCH:=armv6
endif
ifeq ($(ARCH),aarch64)
PKG_ARCH:=armv8

**Comment by antonchen** [comment]
😂我看见你在别的地儿也问这个...

我没有这个设备，无法尝试，只能给你几个建议:

1. 从 [Dreamacro/clash](https://github.com/Dreamacro/clash) 下载带 `mips` 的二进制看看哪个能用
2. 看看 Golang 如何交叉编译这个架构，自行编译一份
3. 直接在 `mips_24kc` 机器上安装 Golang 编译
4. 买买买，直接换一个路由吧

**Comment by zcracker** [comment]
这基本都是软路由啊，，，硬路由基本不满足啊

**Comment by zcracker** [comment]
armv8的硬路由目前还没找到型号啊

**Comment by antonchen** [comment]
@ztechie 

什么？你真准备换路由了？我建议你直接上 x86 软路由，现有路由做 AP，一步到位。或者直接放弃 Clash，或者用别人改好的固件。
另外我查了下 OpenWrt 官方就没几个 armv8 架构的，Golang 程序对 mips 架构支持确实比较乱，参考 [v2ray-core#978](https://github.com/v2ray/v2ray-core/issues/978)

**Comment by zcracker** [comment]
我查了下，实在是不喜软路由啊,市面上目前的牛逼的路由都是ARMV7的，木有V8的 linksys1900acs    The Cortex-A9 implements the widely supported ARMv7-A architecture with an efficient microarchitecture:



arm_cortex-a9_vfpv3 | mvebu | generic | Buffalo | LS421DE | v1
arm_cortex-a9_vfpv3 | tegra | generic | CompuLab | TrimSlice |  
arm_cortex-a9_vfpv3 | mvebu | cortexa9 | Linksys | WRT1200AC | v1 (caiman), v2 (caiman)
arm_cortex-a9_vfpv3 | mvebu | cortexa9 | Linksys | WRT1900AC | v1 (mamba)
arm_cortex-a9_vfpv3 | mvebu | cortexa9 | Linksys | WRT1900AC | v2 (cobra)
arm_cortex-a9_vfpv3 | mvebu | cortexa9 | Linksys | WRT1900ACS | v1 (shelby), v2 (shelby)
arm_cortex-a9_vfpv3 | mvebu | cortexa9 | Linksys | WRT3200ACM | v1 (rango)
arm_cortex-a9_vfpv3 | mvebu | cortexa9 | Linksys | WRT32X | v1 (venom)
arm_cortex-a9_vfpv3 | mvebu | generic | Marvell | DB-A380-DDR3-AP |  
arm_cortex-a9_vfpv3 | mvebu | cortexa9 | Marvell | RD-A370-A1 |  
arm_cortex-a9_vfpv3 | mvebu | cortexa9 | Marvell | Armada A385 DB AP |  
arm_cortex-a9_vfpv3 | mvebu | cortexa9 | Marvell | Armada A370 DB |  
arm_cortex-a9_vfpv3 | mvebu | generic | Marvell | RD-MV784MP-GP |  
arm_cortex-a9_vfpv3 | mvebu |   | PlatHome | OpenBlocks AX3-4 |  
arm_cortex-a9_vfpv3 | mvebu | cortexa9 | SolidRun | ClearFog Pro | v2.1
arm_cortex-a9_vfpv3 | mvebu | generic | SolidRun | ClearFog Base |  
arm_cortex-a9_vfpv3 | mvebu | generic | Turris CZ.NIC | Omnia

**Comment by zcracker** [comment]
mips的cpu感觉要扫进历史的辣鸡堆了，逐渐被ARM的取代了

**Comment by zcracker** [comment]
ifeq ($(ARCH),arm)
PKG_ARCH:=armv7
endif
老大加一行这个吧

**Comment by antonchen** [comment]
已经添加 armv5, armv7，不确定是否一定对。

**Comment by zcracker** [comment]
请大佬验证arm7对不对
root@OpenWrt:# opkg print-architecture
arch all 1
arch noarch 1
arch arm_cortex-a9_vfpv3 10
root@OpenWrt:# cat /proc/cpu
cpu/ cpuinfo
root@OpenWrt:~# cat /proc/cpuinfo
processor : 0
model name : ARMv7 Processor rev 1 (v7l)
BogoMIPS : 1600.00
Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32
CPU implementer : 0x41
CPU architecture: 7
CPU variant : 0x4
CPU part : 0xc09
CPU revision : 1

processor : 1
model name : ARMv7 Processor rev 1 (v7l)
BogoMIPS : 1600.00
Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32
CPU implementer : 0x41
CPU architecture: 7
CPU variant : 0x4
CPU part : 0xc09
CPU revision : 1

Hardware : Marvell Armada 380/385 (Device Tree)
Revision : 0000
Serial : 0000000000000000

**Comment by gitx6** [comment]
@ztechie 你买了哪个路由器？参考一下，谢谢。

**Comment by antonchen** [comment]
@ztechie  看起来是 armv7，但是不能确认我更新的是否是对的，需要 make 才能确定

**Comment by zcracker** [comment]
linksys 1900acsv2
