### ISSUE TITLE
编译的时候提示缺少shadow-su * 这个包去哪里找？

### ISSUE THREAD

**Issue by Anyfc** [antonchen/clash-for-openwrt#3]
Google了下，找到这个：https://openwrt.org/packages/pkgdata/shadow-su，然后是这个：https://github.com/openwrt/packages/tree/openwrt-18.06/utils/shadow

还是没有找到

**Comment by antonchen** [comment]
只是警告吧？编译时可忽略，能编译出来。安装时有 opkg 处理依赖。

**Comment by Anyfc** [comment]
主要是shadow-su这个ipk我也没有找到。。。

**Comment by antonchen** [comment]
opkg install 肯定有的，我就是这样装的
