### ISSUE TITLE
ARMV7启动成功后。内存占用过大，一会就被系统杀掉进程了

### ISSUE THREAD

**Issue by zcracker** [antonchen/clash-for-openwrt#4]
Mem: 106056K used, 404884K free, 1340K shrd, 9452K buff, 34816K cached
CPU: 0% usr 0% sys 0% nic 100% idle 0% io 0% irq 0% sirq
Load average: 0.14 0.11 0.04 1/98 9704
PID PPID USER STAT VSZ %VSZ %CPU COMMAND
9410 1 root S 790m 158% 0% /etc/clash/clash -d /etc/clash

VSZ %VSZ7
90m 158%
不知道为什么会占用这么大

**Comment by gitx6** [comment]
Country.mmdb这个文件有3.8M

**Comment by antonchen** [comment]
占用内存大很可能是载入 IP 库导致的。我现在有事在外地，等我回家可以把 x86 的内存占用发出来参考一下。

**Comment by zcracker** [comment]
> Country.mmdb这个文件有3.8M

正常内存使用是正常的,虚拟内存很大,不知道啥情况留个邮箱交流下

**Comment by gitx6** [comment]
我以前在华硕68U上用v2ray-plugin的时候，也碰到运行几分钟后内存溢出的情况。有人建议用U盘增加swap来解决。

https://mydevtutorials.wordpress.com/2014/01/10/how-to-activate-swap-on-asus-rt-ac68u-router/

试一下用upx压缩这个文件呢？

**Comment by antonchen** [comment]
```
Mem: 110892K used, 3832928K free, 7864K shrd, 3452K buff, 43164K cached
CPU:   0% usr   2% sys   0% nic  97% idle   0% io   0% irq   0% sirq
Load average: 0.00 0.00 0.00 2/92 28405
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
 8082     1 daemon   S     116m   3%   0% /usr/bin/clash -d /etc/clash
```

这是我在 x86 上的内存占用，看起来确实很耗内存

两个建议按照
1.  @wangxin6 所说的添加 swap 试试，但我觉得可行性不高
2. 深水宝找硬改店家硬改内存到 256M
